= Java

== Nouveau cycle de release

Des versions rapide tous les 6 mois et une version _Long Time Support_ tous les 2 ans.

|=============
| version   | sortie         | end support
| *Java 8*  | mars 2014      | décembre 2020
| Java 9    | septembre 2017 | 6 mois
| Java 10   | mars 2018      | 6 mois
| *Java 11* | septembre 2018 | septembre 2022
| Java 12   | mars 2019      | 6 mois
| Java 13   | septembre 2019 | 6 mois
|=============

Prochaine LTS, Java 14 en septembre 2021.

== Distributions

Upstream: OpenJDK

- https://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK Oracle]
- https://adoptopenjdk.net/[AdoptOpenJDK]
- RedHat
- https://aws.amazon.com/fr/corretto/[Amazon Corretto]
- …

== What's new in JDK13 ?

- amélioration du code des sockets
- amélioration de ZGC
- amélioration du _Class Data Sharing_ (améliore le temps de démarrage)

En préversion:

- les bloques de texte
- les switch expression

.JusticeLeague.java
[source,java]
----
class JusticeLeague {
    String toto = """
    {
        "name": "Bruce Wayne",
        "": "batman"
    }
""";
    enum Member {
        batman, superman, aquaman
    }

    String from(Member nickname) {
        return switch(nickname) {
            case barman -> "Bruce Wayne";
            case superman -> "Clark Kent";
            case aquaman -> "Arthur Curry";
        };
    }
}
----

== Future

=== Loom

Projet visant à ajouter du parallélisme en java.
grren thread/continuation/end-tail
https://wiki.openjdk.java.net/display/loom/Main

=== Valhalla

Projet switch/value object…
https://wiki.openjdk.java.net/display/valhalla/Main

=== Sumatra

Utiliser des GPU
https://openjdk.java.net/projects/sumatra/

== Graalvm

Projet open source développé par Oracle pour palier à certaines limites de HotSpot.

https://www.graalvm.org/

4 parties distincts:

- *GraalVM Compiler* un compilateur java (remplace une partie de hotspot)
- *GraalVM Native Image* java compilé en natif (ahead-of-time)
- *GraalVM SDK* implémentation d'autres langages
- *LLVM Runtime and JavaScript Runtime*
